export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL';
export const STUDENT_DETAILS_RESET = 'STUDENT_DETAILS_RESET';

export const VOLUNTEER_DETAILS_REQUEST = 'VOLUNTEER_DETAILS_REQUEST';
export const VOLUNTEER_DETAILS_SUCCESS = 'VOLUNTEER_DETAILS_SUCCESS';
export const VOLUNTEER_DETAILS_FAIL = 'VOLUNTEER_DETAILS_FAIL';
export const VOLUNTEER_DETAILS_RESET = 'VOLUNTEER_DETAILS_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';
export const GET_STUDENTS_RESET = 'GET_STUDENTS_RESET';

export const GET_VOLUNTEERS_REQUEST = 'GET_VOLUNTEERS_REQUEST';
export const GET_VOLUNTEERS_SUCCESS = 'GET_VOLUNTEERS_SUCCESS';
export const GET_VOLUNTEERS_FAIL = 'GET_VOLUNTEERS_FAIL';
export const GET_VOLUNTEERS_RESET = 'GET_VOLUNTEERS_RESET';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';
